# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

job_build:
  stage: build
  script:
  - npm prune
  - npm install
  - npm run build --production
  artifacts:
    paths:
    - dist/
    - coverage/


job_deploy_demo:
  stage: deploy
  dependencies:
  - job_build
  script:
    - bash deploy-gitlab.sh
  environment: demo

job_deploy_testreport:
  stage: deploy
  dependencies:
  - job_build
  script:
  - bash <(curl -s https://codecov.io/bash)
